# Generated by Django 5.0.1 on 2024-01-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('exist', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('base_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.base')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identification_code', models.CharField(max_length=255)),
                ('classification_id', models.IntegerField(max_length=255)),
                ('retention_period', models.DateField()),
                ('usage_policy_start_date', models.DateField()),
                ('usage_policy_end_date', models.DateField()),
                ('physical_condition', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('annotation', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('approval', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], default='option1', max_length=20)),
                ('base_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.base')),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.folder')),
            ],
        ),
    ]
