# Generated by Django 5.0.1 on 2024-01-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='classification_id',
            field=models.IntegerField(),
        ),
    ]
